version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: chainlit_db
    environment:
      POSTGRES_DB: chainlit
      POSTGRES_USER: chainlit
      POSTGRES_PASSWORD: password
    volumes:
      - chainlit_data:/var/lib/postgresql/data
    ports:
      - 25433:5432
    restart: always
volumes:
  chainlit_data: